<template>
  <el-container>
    <el-main>
      <el-button type="primary" @click="dialogVisible = true" style="margin-bottom: 20px;">添加药品</el-button>
      <el-button @click="reorderMedicines" style="margin-bottom: 20px; margin-left: 10px;">重新排序</el-button> <!-- 添加重新排序按钮 -->
      <el-button @click="deleteSelectedMedicines" style="margin-bottom: 20px;" :disabled="multipleSelection.length === 0">批量删除</el-button><!-- 多选框列 -->
      <el-button @click="exportToPDF" style="margin-bottom: 20px; margin-left: 10px;">保存数据</el-button>
      <el-table :data="medicines" ref="multipleTable" @selection-change="handleSelectionChange" style="width: 100%; height: calc(100vh - 200px); margin-top: 20px;" stripe>
        <el-table-column prop="mno" label="编号" width="100" sortable></el-table-column>
        <el-table-column prop="mname" label="药品名称" width="300"></el-table-column>
        <el-table-column label="服用方法" width="150">
          <template slot-scope="scope">
            <span>{{ scope.row.mmode }}</span> <!-- 在浏览时显示文本 -->
          </template>
        </el-table-column>
        <el-table-column prop="mefficacy" label="药品功效" width="750"></el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template slot-scope="scope">
            <el-button @click="editMedicine(scope.row)" type="text" size="small">编辑</el-button>
            <el-button @click="deleteMedicine(scope.row.mno)" type="text" size="small" style="color: red;">删除</el-button>
          </template>
        </el-table-column>
        <el-table-column type="selection" width="50"></el-table-column>
      </el-table>

      <el-dialog :title="isEditing ? '编辑药品' : '添加药品'" :visible.sync="dialogVisible">
        <el-form :model="currentMedicine" label-width="100px">
          <el-form-item label="药品名称" prop="mname">
            <el-input v-model="currentMedicine.mname" required placeholder="请输入药品名称"></el-input>
          </el-form-item>
          <el-form-item label="服用方法" prop="mmode">
            <el-select v-model="currentMedicine.mmode" placeholder="请选择服用方法" required>
              <el-option label="内服" value="内服"></el-option>
              <el-option label="外用" value="外用"></el-option>
            </el-select>
          </el-form-item>
          <el-form-item label="药品功效" prop="mefficacy">
            <el-input type="textarea" v-model="currentMedicine.mefficacy" required placeholder="请输入药品功效" rows="4"></el-input>
          </el-form-item>
        </el-form>
        <span slot="footer" class="dialog-footer">
          <el-button @click="dialogVisible = false">取 消</el-button>
          <el-button type="primary" @click="saveMedicine">{{ isEditing ? '保存' : '添加' }}</el-button>
        </span>
      </el-dialog>
    </el-main>
  </el-container>
</template>

<script>
import request from '@/utils/request';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import './Genericons-normal'
import '@/assets/font/Genericons.ttf'

export default {
  name: 'Medicine',
  data() {
    return {
      medicines: [],
      dialogVisible: false,
      isEditing: false,
      currentMedicine: {
        mno: null,
        mname: '',
        mmode: '',
        mefficacy: ''
      },
      multipleSelection: [], // 存储选中的记录
    };
  },
  methods: {
    // 处理多选框的选中状态
    handleSelectionChange(val) {
      this.multipleSelection = val;
    },
    // 获取药品列表
    fetchMedicines() {
      request.get('/medicine/find')
          .then(response => {
            console.log('Response:', response); // 打印响应数据
            if (response && response.code === "200") {
              console.warn('获取药品数据:', response.msg);
              this.medicines = response.data.sort((a, b) => a.mno - b.mno);
            } else {
              console.warn('没有药品数据:', response.msg);
              this.medicines = [];
            }
          })
          .catch(error => {
            console.error('Error fetching medicines:', error);
            this.medicines = [];
          });
    },
    // 保存或更新药品信息
    saveMedicine() {
      const method = this.isEditing ? 'put' : 'post';
      const url = this.isEditing
          ? `/medicine/update/${this.currentMedicine.mno}`
          : '/medicine/save';

      request[method](url, this.currentMedicine)
          .then(response => {
            this.dialogVisible = false;
            this.$nextTick(() => { // 确保在下次 DOM 更新后执行
              this.fetchMedicines();
              this.resetForm();
            });
          })
          .catch(error => {
            console.error('Error saving medicine:', error);
          });
    },
    // 编辑药品信息
    editMedicine(medicine) {
      this.currentMedicine = { ...medicine };
      this.isEditing = true;
      this.dialogVisible = true;
    },
    // 删除药品
    deleteMedicine(mno) {
      this.$confirm('确认删除此药品吗?', '警告', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        request.delete(`/medicine/delete/${mno}`)
            .then(response => {
              this.fetchMedicines();
              this.$message.success('删除成功');
            })
            .catch(error => {
              console.error('Error deleting medicine:', error);
            });
      }).catch(() => {
        this.$message.info('已取消删除');
      });
    },
    // 批量删除
    deleteSelectedMedicines() {
      this.$confirm('确认删除选中的药品吗?', '警告', {
        confirmButtonText: '确定',
        cancelButtonText: '取消',
        type: 'warning'
      }).then(() => {
        // 获取选中的经办人编号列表
        const mnos = this.multipleSelection.map(item => item.mno);

        // 发送批量删除请求
        request.delete('/medicine/deleteBatch', { data:  mnos  })
            .then(response => {
              if (response.code === "200") {
                this.$message.success('批量删除成功');
                this.fetchMedicines(); // 刷新列表
              } else {
                this.$message.error('删除失败: ' + response.msg);
              }
            })
            .catch(error => {
              console.error('批量删除出错:', error);
            });
      }).catch(() => {
        this.$message.info('已取消删除');
      });
    },
    // 重新排序药品编号
    reorderMedicines() {
      console.log('重新排序按钮被点击'); // 调试信息

      const updatedMedicines = this.medicines.map((medicine, index) => ({
        ...medicine,
        mno: index + 1 // 新的药品编号从 1 开始
      }));

      console.log('更新后的药品数据:', updatedMedicines); // 打印更新的数据

      // 发送更新请求到后端
      request.put('/medicine/reorder', updatedMedicines)
          .then(response => {
            console.log('重新排序的响应:', response); // 打印响应
            if (response && response.code === "200") {
              this.$message.success('药品编号重新排序成功');
              this.fetchMedicines(); // 重新获取药品列表
            } else {
              this.$message.error('重新排序失败: ' + response.msg);
            }
          })
          .catch(error => {
            console.error('Error reordering medicines:', error);
          });
    },
    // 重置表单
    resetForm() {
      this.currentMedicine = {
        mno: null,
        mname: '',
        mmode: '',
        mefficacy: ''
      };
      this.isEditing = false;
    },
    exportToPDF() {
      const doc = new jsPDF();

      //试图解决中文乱码问题，没法解决
      //doc.addFileToVFS(`Genericons.ttf`, 'AAEAAAANAIAAAwBQRkZUTXvN3KoAAFdkAAAAHE9TLzJkLHXFAAABWAAAAGBjbWFwqXKzoQAAAvAAAAGyY3Z0IABEBREAAASkAAAABGdhc3D//wADAABXXAAAAAhnbHlm6Bdf1wAABdgAAElgaGVhZA++/14AAADcAAAANmhoZWEQuAgGAAABFAAAACRobXR4WPBTcgAAAbgAAAE4bG9jYeRT9nYAAASoAAABMG1heHAA6QEZAAABOAAAACBuYW1lMd/vXAAATzgAAAI6cG9zdPYil78AAFF0AAAF6AABAAAAAQAAo5kp0l8PPPUACwgAAAAAANRQ2TAAAAAA1FDZMf/5AAAIBggAAAAACAACAAAAAAAAAAEAAAgAAAAAuAgA//kAAAgGAAEAAAAAAAAAAAAAAAAAAAAFAAEAAACXAOgAEAAAAAAAAgAAAAEAAQAAAEAALgAAAAAABAfzAZAABQAABTMFmQAAAR4FMwWZAAAD1wBmAhIAAAIABQMAAAAAAAAAAAABEAAAAAAAAAAAAAAAUGZFZACAACD1FwgAAAAAuAgAAAAAAAABAAAAAAAAAAAAAAAgAAEC7ABEAAAAAAKqAAAAyAAACAACAAEAAIAAgAIAAoABAAIAAAABAAAAAAAAgACAAoAAgACMAQAAgACrAAAAoACAAIAB2ACAAP8AgACMAIAAjAGAAM0BAAEAAIACAAEAAYABAAEAAgABAAEAAQABVQEAAQABAAAAAAACgACAAYABAAGAAQABgAEAAQD/+gCAAgABgAJgAAABAAGAAYAAUwEAAYAAgAGAAwABgAISAYABgAAABIABgAIAAgABAAGAAIAAgAIAAgABgACgAQABAAIAAgABAAEAAgABAACAAQABAAEAAIAAgAEAAPMAZgAAAAAAAAAAAYABAAEAAYACAAKAAYAAgAEAAKAAgAAAAIAEQAGAAQABNwCAAFQBbgCAAYABAAHGAYAAgAGAAIAAgACAAQAAgACAAQAAAAADAAAAAwAAABwAAQAAAAAArAADAAEAAAAcAAQAkAAAACAAIAAEAAAAIPEJ8gnyGfIm8wj0CfQZ9Cn0OfRJ9Fn0afR29Rf//wAAACDxAPIA8hDyIPMA9AD0EPQg9DD0QPRQ9GD0cPUA////4w8EDg4OCA4CDSkMMgwsDCYMIAwaDBQMDgwIC38AAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBgAAAQAAAAAAAAABAgAAAAIAAAAAAAAAAAAAAAAAAAABAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQFEQAAACwALAAsACwAWgCEAMwA8gEAARwBRgGUAc4CCAKyA0wDpAPgBBIEwgUWBWIFvgYwBsIG5AckB0gHgghICUAKoAr0C4IMOAyEDVINpA3mDiIOjA6uDsoO6A8yD1QPmg/wEFoQmBDOEQwRVhGwEhoSPBJeEqgSxhLiEv4TLBNEE4gTwBQSFFIUghSWFLIU+BUGFRwVWhWIFfQWIBZQFmIWfBaUFqgWvhbMFtoW8BdOF34XvBfwGDIYbBiUGLYY5Bk+GXoZqhnAGc4Z5Bn6GggaOBp6GrIa5Bs6G1AbZhuYG7wb5hwqHGQcohzQHPAdJB1UHYYdvh3YHgAeRh9eH4gflh+iH7AfviASIEggoCEwIWghqiIsIkgibiKiIrAi5CL+IzAjTiN4I8IkWCSMJLAAAgBEAAACZAVVAAMABwAusQEALzyyBwQA7TKxBgXcPLIDAgDtMgCxAwAvPLIFBADtMrIHBgH8PLIBAgDtMjMRIRElIREhRAIg/iQBmP5oBVX6q0QEzQAAAAYCAAIABgAFgAADAAcACwAPABMAFwAAASEVIQUVITUFNSEVATUhFSUVITURNSEVAgAEAPwAAoD9gAMAAQD9gAKA/QD/AAMABYCAgICAgICA/wCAgICAgP6AgIAAAgEAAQAHAAcAAAsAEwAAACAEEhACBCAkAhASADI2NCYiBhQDLwGiAWHOzv6f/l7+n87OAcjUlpbUlgcAzv6f/l7+n87OAWEBogFh/M6W1JaW1AAABACAAYAHgAaAAAcAFwAbACoAAAEFESERJRMhADI+AjQuAiIOAhQeAQMVBTUAMh4BFRQOAiMiLgE0NgWAAgD5AAIAgAIA/qW2pnhHR3imtqZ4R0d4//8AAqmuk1YzVXdBV5NWVgWAgPyAA4CAAQD7gEd4prameEdHeKa2pngD+WBAoP7AVpNXQXdVM1aTrpMABACAAgAIAAWAAAMABwALAA8AAAEhESEBESERAREhESERIREEgAOA/ID8AAOA/oABgPyAAYAFgPyAAgABgP6A/gABgP6AAYD+gAAAAAECAAGABoAGgAACAAAJAgIABID7gAaA/YD9gAABAoABgAWABwAADQAAARQGBxEFES4BNTQ2IBYFgI9x/wBxj+EBPuEFgHvFKP3ogAKYKMV7n+HhAAIBAAGABwAGAAALABcAAAERIREUDgEjETI2NQEhERQOASMRMjY1IQEAAoCJ7ItqlgIAAoCJ7Itqlv6AA4ACgP2Ai+yJAQCWagKA/YCL7IkBAJZqAAICAAGABYAHAAAZADQAAAAgFhURFAYHNTY1ETQmIgYVERQXFS4BNRE0Fx4BFREUBiAmNRE0PgE3FQYVERQWMjY1ETQnA7sBCrtqVkBxnnFAVmrAVmq7/va7MVY5QHGecUAHALuF/oBhniaXOlQBgE9xcU/+gFQ6lyaeYQGAheAmnmH+gIW7u4UBgEB1VxmXOlT+gE9xcU8BgFQ6AAIAAADAB4AHAAAQACMAAAEyFhURFAYrAREBITchMjY1ATIWFREUBiMhAREjIiY1ETQ2MwaAapaWaoD+QP61gAGLn+H+gGqWlmr+QP5AgGqWlmoGAJZq/oBqlv5AAcCA4Z8CgJZq/oBqlv5AAcCWagGAapYAAwEAAYAGgAaAAAUAEAAeAAABIQERASEBHgEUBgcnNjU0JwEeARAGByc+AjU0JicBAAGAAYD+gP6ABA82Ozs2WktLARBYY2NYWy9CJU9HBQABgPsAAYACEDaMnIw1WktqaksBEFnq/vzqWVsvcYRGaLtHAAABAAAALQgACAAAdwAAACAEHgISFRQCBgQHBiY1NDY1NCYnPgY1NCc+AiYnLgEOAgcmJwYHLgMPAQ4BFB4BFwYVFB4FFwYHDgIuAScuBCcqAQ4BFhceBBceBjcUFhQVFAYnJiQmAjU0Ej4CA3UBFgEK4L2ESmm5/v6YIyMBJx41WWNNSTAcaQYJCQ8TBA4yPGM3eYeHeTdiPy4KChAPCAkEaRwwSE5iWTU0DRYuRz9GGgIJHSI2HQQMGQkRGgMJHRoiDQEGFyA3RmI8ASMjl/79uWlKhL3gCABKhL3g/vaLp/7I+78yByAYBMNSQ2AaBhMkMk5iiFOgcg8oSF8xAQMFEjElIgEBIiUxEQYCAihQOTccC3OfUoliTjIlEgYuWwoOBRA1LQQNIxsYAgcLGhIBBhgeOCEEDSkeKg4KESRPMQoYIAYzvvsBOaeLAQrgvYQAAAAABwAAAAAIAAgAAAgAEQAdACoAMgBAAFAAACUyNwIDBgAHFiU2EjckBR4BEgEVFBIXNgA3JicMAQEOAgceAhc2BBcCAQYABxYkNwITIgYjFhM+BDcmLAEgBAASEAIABCAkAAIQEgAEALW7Ia/e/ohq2ANInMwY/uz+1A46W/qddGx9AaznEED+5v5xBWlHtvc8Fh0nBqoBTHoa+zrC/vEvwgH0io2tIIAgZsoGoE2LaSl+/rf+eQGcAXsBE6Sk/u3+hf5k/oX+7aSkAROAUAEsAYRK/tHHwKBsAVTALi4bmP7KAolAp/7PeM0BNk0wgFYyAdg5X2oeHTNUDCEGGwEdAfNV/rvWFkguARoBNhCm/qYCOiA+QiR+koCk/u3+hf5k/oX+7aSkARMBewGcAXsBEwAAAAABAIABLAeABt0AOQAAAQYHFhUUDgQEIyAlFjMyPgE3LgEnFjMyNy4BPQEWFy4BNTQ3FgQXJjU0PgIzMhYXNjcOAQc2B4BLbQItWoCw0P7+jv7O/v8sLFWjkT93vSMlIDEwf6hOWEtYMooBiuIKOmOIS06LM31sFFQ5bgYwcE4bFWnUzbudc0GlBSZGMQOObwcNGcuEBSsDMqJeY1aqywspK0qIYzo9NxlAQGkiDQAAAAEAgACAB4AHgAAnAAABMhYVERQGIyERIRMhPQE0NjMXNyYjIg4CHQEjETMRISImNRE0NjMGgGqWlmr+5gEODP7mK0KmBU1pXpJYLP7+/SxqlpZqB4CWavsAapYCxwEEwAw8NwHyCjZfdUTs/vz9OZZqBQBqlgAAAAECgACABecHgAAgAAABIQMhESERIxEzETQ+BDMyFh8BAyIjIg4CHQMEngFJD/7G/sDe3hctSF5+SjdqGhoHXWQoNBoJBPj+0fy3A0kBLwECNGBXSDYdBgMD/uYRJS0iAwIJAAAFAIAAgAeAB4AAEwAZACEAZABuAAAAIAQWEhUUDgQjIiQmAhASNgEUEhcBBgEyNyYnCwEWEwETNjc+AzU0LgEnLgg1NDYzMhcmJCMiBAYHMjMyNj8BNhYGBwYHARMDJy4BNhcWMzI2PwE2FgYHBiUWFRQHAzYSNTQDSgFsAUzwjkFzpsToerb+tPCOjvD+3PrN/n9GAyaKggQC+PJw4wEjUAIEEA4TBxcYFAEXBRIFDgQHAk46AQlu/umbiv7/zkgbGSVsIyIVEw4ULDABJbB+VBQPFBSFTyZrIyMVEw4VKwIjBT32t9oHgI7w/rS2eujEpnNBjvABTAFsAUzw/Q7s/ntkBB2d/C8uBQYCp/1BIQSg/J4BDAYMMTFGMxguWTUiAiUIIAscDxgVCzlWAWRwW6NuBQIDAR8iAwUC/JcCEQFYBwIiIAEKBQIDAR8iAwUHKCuHmv05agFz284AAAAAAgCMAfMHAAaNADEAPQAAASEWFRQOBCMiLgI1ND4CMzIWFwcuCSMiDgEUHgEzMj4DNyElMxUjFSM1IzUzNTMC2gImDSZFZHyWUnbanl9iodhydclCmgIUCRYQGRYeHiQSZatkZKtlQXBINhkE/rQDpoCAgICAgASAJzNSlnxkRSZfntp2ddueX05MmQENBw0ICwcJBANjq8qrYyQ2RTsZzYCAgICAAAAAAwEAAQAHAAa9AAMAEgAxAAABIREhJyMiJjU0NjMyHgEXFA4BASERNCYjIg4BBwYVESESJyEVPgYzMh4CFQJd/rYBSqUCUWVnUzdULAEsVgUQ/rdRVitHKg0L/rcEBAFJCxUgIS8zQiRSiWc5AQAD34diSUphLU0xME0u+5oCEml3JTMgGzb91wOCXY0RHCMbGxMLN2utbwAEAIAAgAeAB4AADwATACAAPAAAATIWFREUBiMhIiY1ETQ2MwERIRETMjY1LgEjIgYVFBYzARE0JiMiDgIHNSEWEBUHIRE0Nz4CMzIWFREGgGqWlmr7AGqWlmoBF/75g0RRAVBCQ1JRQQQ7p4gyUTgiEP74AQEBCAgKIjkiRUEHgJZq+wBqlpZqBQBqlvoAAxn85wOFTzo8TU47Ok/8ewHHr7YZKycYcCH+c7W2AbsrFRopHV9U/lgAAQCrAAAHUQgAAFAAAAEyHgQVFA4EIyImJwIHBgcnJjcTLgI1NDYzMhYVFA4BBwYWMzI2EjU0LgIjIg4EFRQXHgEHDgEHDgEnLgI1ND4FBDF22a6OYDQtU3mWtmRjryJJECJdlQcdogQOFo1mU1gmPA4XemR1uWJFg8h9XauHbkknUxIHBwMUAgcjFlV2NyRMbJez4wgAN2KIoLVde+K/nG08XUD+3Th7kzaoegKwCSFpNIy7a1Izk8E5Y5C4ATG2aLGBSi5RcIaYUJViFRoYDE8KGBEJI5S8cE2em414VzIAAAAAAQAAAAAIAAgAAGMAAAAgBB4CEhACDgIEIyInNjcTHgEzMj4BEjU0LgMjIg4EFRQWFxY2Nz4BNzYmJyY1ND4CMzIeAhUUDgEjIi4BNz4CNTQmIyIOARUUFh8BAgcGFyYAAjU0Ej4CA3UBFgEK4L2ESkqEveD+9ouUjkscSByNUXnPkFE7cpzNc3bRnn5PKWpnEhwFAhECBQUOREeAwHFlo2o4UJZeNVQlDAsxHkdDNlo1EAgJcRMXBbX+7JxKhL3gCABKhL3g/vb+6v724L2ESip4YwEaNUtruwEDlVutlG9AN158kJVKitMqCA4TCEAKFBURT3lhsodRPGmPVZP4lTVbNS+cdypCV0R6SytRExP+JVNiiU8BFwF2zosBCuC9hAAAAAIAoAJgB2AFoAAHAA8AAAAgFhAGICYQJCAWEAYgJhAFFAFY9PT+qPT9dAFY9PT+qPQFoPT+qPT0AVj09P6o9PQBWAAAAQCAAQAHkAcMACIAAAEEAwIBACMiAwInAiMiByc2NzY3NhMSFxIzMjc2NzYjIgcSBnsBFBAM/p/+kv2dbG4iUVwUeVSFgbBZ0TE0FDxJOHFwCBCIQEWEBwAI/qX+/f49/ikBHwGPfgEfVGx0c5gIFP7Q/rhP/vGwsFyYHQGtAAACAIABgAeABoAADwASAAABMhYVERQGIyEiJjURNDYzCQIGAJ/h4Z/8AJ/h4Z8BAAKA/YAGgOGf/gCf4eGfAgCf4fwAAYABgAABAdgAgAYoB4AAIgAAAREhESERFBcWFxYzMjcRBgcGIyInJicuATURIzU2NzY3NjcEQwGp/lcREC08TIiHc11dbHtfXkNCNMZqS0suLREHgP47/uf+NJwsLBokWP7mNhYWHx85OoF7AnX9I0BAWlmLAAAAAAUAgACMB2cHgAAjAGIAdgB+AIkAAAEhIgcOAQcGFRkBFBceARcWMykBMjc+ATc2NRkBNCcuAScmIyUyFhcyFx4CFx4BFxQeAhUZARQHDgIHDgEHIg4CIykBIicuAicuASc0LgI1GQE2NzY3NjcyPgIzATIeAxQOAyMiLgI0PgICMjY0JiIGFAA0NjIWFRQOASMiBAD+mnQzOVoTGhoTWjkzdAFmAWZ0MzlaExoaE1o5M3T+mr1oQY1NIiY6GCMtFhUICSYRFSkXG0g3Ak0kRyD+jf6NjU0iJToYJC0WFAgKFB8RVkxNAk0kRyABc0yMclUuLlVyjExeq3tJSXurH/qpqfqpApk8VTwbMBsrBtoaE1o5NHP+mv6ZczM6WRMaGhNZOjNzAWcBZnM0OVoTGqYDCiYRFSkYGkg3Ak0kRyD+jf6NjU0iJTsXJC0WFQcKJhEVKRgaSDcCTSRHIAFzAXOMTkRVTScUCAr+TS5VcoyYjHJVLkl7q7yre0n9Dan6qan6AixVPDwqHC8cAAgA/wEBBwEG/wCOAJIAlgCZAJ0AoQClAKgAAAEUFREUFTAGFTAGFRQGMRQGBwYxBgcUBjEGBwYVDgEHBgcGIwYPAQEGIicBMC8BJicwJjUmJyYnLgE1Jic0JyYnJjU0JjUwJjU0NRE0NTA2NTYxNDc2NzY1Mjc0NzY3Njc2NzY3Nj8BMDcBNjIXATAWMTAWMxYXFhcWFxYXFhcWFRYXFhUwFhUwFhQXFDEWAREFNwkBFyUFFTcBESUHJTcnBwkBJwUlNQcHAAEBAQEBAQECAQECAgECAQECAgEBAgH9QhEoEf1CAQMBAwIBAwEBAgICAQEBAQEBAQEBAQEBAQECAQECAQECAgEBAgIDAQK+ESgRAr4BAgECAQIBAQICAQEBAgIBAQIBAQH9QgEe5/13/fvnAR79xqUBlf7i5wJH6enpASsCBef+4gI6pQTyBQT+LQIHAgEEAQECAQMBAwICAQICAgIBAQIBAQEDAQIB/i0LDAHTAQIBAgIBAQICAQIDAgICAgECAwIBAQQBAgEEBAHTBAUCAQUBAgQBAgIEAQIBAwECAgEBAgECAgEB0wsL/i0BAgIBAgEBAwEBAwECAQMCAgEEAQIBBQECAU/+zb+aAVj+qJq/oNxu/b4BNL+bTpycnP2+AViav6HcbgAAAAAEAIAAgAeAB4AAEwA8AL4A5wAAATIEFhIQAgYEICQmAjU0PgQXJgQHBgIXHgEXFgQ3BiMiLgI1ND4BNzY3PgE/AT4CMzIEFyYnJiQTFgYHBgcGJxYzMj4CNTA0MS4BJyYkBwYHBhceARcWNjc2JicuAQYHBgcGFx4CFxY2Nz4BNzYmJy4CJyYOAQcOARceARcWNy4BJyYnJjY3PgEXHgEXHgEHDgMHBiYnLgE3PgIXHgMHDgMnLgInLgE3PgIXHgIBMiQ3NjU0LgInHgIXFgIHBgQnJiQnJhI3NiQ3NjcGBAYCFRQSFgQEALYBTPCOjvD+tP6U/rTwjkFzpsTo057+1m1tZBQRpnx4ASB7SUtvzJRXJEAuAgECCQMBQaTEZ6MBHmEgJWj+25ADKipWi3R2VFpgr35LC2pUZv70bXQ9PgoImm1u3zs+F0suhYg1VhMVMxAsNR0sWiYmNAgIEhkQKzIbGjQtEhsXBQYrHygvLkgNAQEOCRUWRSYmRhQVBRIJGyIoFitbISIlAwJWhUIzVS8MFRJQZnY4JEEzERsJEhd7qFRXkFX+e+wBiGY7V5bJc02DYRo2SHNw/renp/7pR0oNV1gBLbIREpv+6cl2gdsBLgeAjvD+tP6U/rTwjo7wAUy2eujEpnNBlwh1b2v+2ZWU/0lIDjkVWJPMcEaIdTICAQIKAgFLbDuMezMtfpX9CkOGOHMqIxwiS36vYAJrvz5NFDs+aWt8eMMeIVJdW+JLMy0UJz1gYVUbKx8HCw4XF0cpKlQhFyETAgIMGhIbSiUlPhEWBgE4KwIBH0kdHiECASsjI1QnFCEaEwQJGR8gWTBBay4RDEVebzU0VC0IFg4vPSQ3ezxPeTUPDG2j/If4zIaEddGbaxQgbY1Rl/6ueHtwHRrfn5wBbZmb0h4EAgyK2P7enqb+0tuCAAAAAAIAjAHzBwAGjQAxAD0AAAEhFhUUDgQjIi4CNTQ+AjMyFhcHLgkjIg4BFB4BMzI+AzchJTMVIxUjNSM1MzUzAtoCJg0mRWR8llJ22p5fYqHYcnXJQpoCFAkWEBkWHh4kEmWrZGSrZUFwSDYZBP60A6aAgICAgIAEgCczUpZ8ZEUmX57adnXbnl9OTJkBDQcNCAsHCQQDY6vKq2MkNkU7Gc2AgICAgAAAAAEAgAB/Bz0HggBmAAABHgcGBw4FLgEvAREOCAcOAS4BLwERHgI2NxEhER4DPgQ3Ni4GIyciJg4GBw4BHgMfAQcuBD4BNz4DHgMXBZ4HGUlFWEQ7Gg4fK2xvd3BoV0ASEgEBBggRFCAlNB00blRFEhMhREM4EAE4BhRAP1hNUj8xCgIkPlJbXFNBExMEEDM0S0ZTR0gcGxkDERoZCQnhBxc6KR0LSENFqKewoph7XBoHKQMMKjJVXYOOt2JZiVM3EwUNDQcG/usCBxYXIB4jHh0LEgIZHgwNARgiKw4kLQOy/eYCBQsEBRMtQ2tFTIJbSiwiDwgBAQMGDxgoM0stLWBRTDosDAvJCSBpbqWhxlxOcjsgAg4cGQoAAAAAAgCMAIAHdAeAACkAgQAAARYHFA4CIyInBiMiLgQ1NDcmNTQ+AzMyFzYzMh4FFRQBNjU0JyYnJicmJyYnJicmJyY1NDc2MzIXFhcWFxYzMjc2NTQnJicmJyYjIgcGBwYVFBcWFxYXFhcWFxYVFAcGIyInJicmJyYnJiMiBwYVFBcWFxYzMjc2B0EzAU2DtWR5bU9Mctu4nG08EUMxW3iVUI13SkZivqWTc1Ms/mY7IiM9O1RSaVYeICQgExA0N1tiKyohHBcZLzQjIhkaODhTVXCOaWw4OTc1W1iFXD44IiE+QmhOLS4YGhcVHB8sNiIjNjRXd7aZbnADQmdyZLWDTToOPWycudpzVFVyhVCVeFsxSwwsU3OTpb5iXf7KVGhYPTwoJxsaFxMJCRIPFxUcLiIkICA+LhUWJCQtLjIwLCwaGicpSUpgZkRCJyYcFBIRIR4yPyosFhUhITUwGBkgIS9LTUwvPy4uAAAAAAEBgAEABoAHAAA0AAABFA4BBxYVFA4BBxYVFAYrATIWFAYjISIuAisBETMyPgI1ND4DMzIeARUUBg8BITIWBoAWJxkWFicZFks1QDVLSzX+QEF0R1oqgMAxbmFAAQcMGhIhWUYQCAgBoDVLBAAbMSQIIScbMSQIISc1S0tqSygwKAKAXqH4iQURLSEcVJpSVaAlJksAAAAACADNAY0HMwdzABEAHQAnADAAPwBIAFAAiQAAATYyFhQHBiMiJyY0NjIXFjMyARQGIyImNTQ2MzIWJDIWFRQGIiY1NCU2NTQmIyIHFgEyJDY1NCYkIyIEBhQWBAEUFzY3JiMiBgAiBhQWMjY0ExQGBxYVFA4BBCAkLgE1NDcuAjU0NjMyFhc2NxM2NzYXBT4BMzIWFAYjIi4BJyUDFhc+ATMyHgEEyA8qHg9WubtWDx4qDziPkf7vQi4uQUEuLkIBRFxCQlxCAiErOSktH1P9i6sBI6qq/t2rrP7dqqoBI/3iKC9VHSwpOgUtPy4uPy2mOC4OdMX+8P7W/vDFdRAdKxl2UzFTHLflXAUSEhUBORhSMUppaUovTzED/vpN3q8cVTI2XDYDCA8eKw9WVg8rHg84AQYuQkIuLkJCQkIuLkJCLi49HzApOSc9/WdqtWtstmpqtta2agKbLxxMPSQ5AlQuPi4tQP2wN1sbMjFluYVPT4W4ZTI2EjNBI1N2LSZhCQHJFgsMBUgpMWmUaS1NLjz+fgxgKC42XAAAAAIBAAIABwAGgAAjADcAAAE1NC4BIyIGFQMOAiMiLgI9ASEVFBYyNjURPgEzMhYXFQcFIRUUDgEjIi4BJzUXNxUUFjI2NQRRFiUWIi8BAVydXUWAXDYBBy9ELwXHi4vIBJ0BPwEHXJ5dXZ5cAWmdL0QvBNFcFiUVLiL+H1qZWTVbfUTRziEvLyEB54i9v4hrLX/RW5xaWZpb0jAu1CEvLyEAAAAAAgEAAYAHAAcAAA8AJAAAATIWFREUAgQgJAI1ETQ2MwE2NCYiBwkBJiIGFBcBNx4BMjY3FwYAapbO/p/+Xv6fzpZqA9omS2ol/tr+2iVqSyYBaQUROUQ5EQUHAJZq/oDR/p/OzgFh0QGAapb9piVqSyb+2wElJktqJf6WBB0jIx0EAAAABQCAAL4HgAdCAAMABwALAA8AFwAACQMRCQw3FQkBNRcCjwFx/e3+kwFtAhP+jwFxAhMBbf3xAg/+k/3tAXH+kAFynv3w/fCeB0L+zP63AST9uQEj/rj+zAE0AUj+3f6nA6D+3AFJATT7+f7NZ3P+wgE+c2cAAAAAAgIAAP4GWQcAAB4ARQAAATIWBwMCBw4EKwEiBgcBDgEmJy4BNRE0PgIzATc2JiMhIgYVERQ3Ejc+ATsBMjY3PgE3NiYjISImPQE0NjMhMj4BBcZYOhQ0WQUFBhQZLx76CAUH/ncOKiALFB8PHzwoAuEiBRoT/W4VHQXzGhQdH90UGwMCHgMEHhP+8RsjIxsBPwsWEAcAYmL+/v4+FBQVKBUSAgj+ORANAwUHKygFFRcsLBz+b7MWHyAS/AgGBQEjIhgOGg4InA0UIyIbJxshDBMAAAABAQAAwAcABgAAEgAAATIWFREUBiMhAREjIiY1ETQ2MwYAapaWav5A/kCAapaWagYAlmr+gGqW/kABwJZqAYBqlgAAAAEBgAIABoAGAAALAAABIQEhESEXIRUhAzMCwAPA/wD8AAGAQAHA/YCAgASA/YAEAICA/wAAAAAAAgEAAQAGAAYAAAQADAAAASERCQEAMjY0JiIGFAQAAgD9AP4AA8tqS0tqSwYA/gD9AAIAAYBLaktLagAAAwEAAYAGgAcAAA8AHwAlAAAAIAQWEhACBgQgJCYCEBI2ATI+AjQuAiMiBAIQEgQTEQEHAREDMQEeAQW8cHC8/vv+4v77vW9vvQGUddWbW1ub1XWc/vaamgEK3AEqW/6xBwBvvf77/uL++7xwcLwBBQEeAQW9+29bmtbq1ppbmv72/sj+9poEAP5a/tdbAVAB2gAAAAICAAGABgAGgAAHABEAAAAiJjQ2MhYUAzIWFREhETQ2MwRq1JaW1JaAn+H8AOGfBICW1JaW1P7q4Z//AAEAn+EAAAAAAwEAAYAGgAcAAAsAGwAsAAABIREhESE1MxUhNTMTETQmIyEiBhURFBYzITI2ATIWFREUBiImNREjIiY0NjMFgAEA+oABAIACgICASzX8gDVLSzUDgDVL/cAaJiY0JkAaJiYaBoD7AAUAgICA+4ACgDVLSzX9gDVLSwK1Jhr+ABomJhoBwCY0JgAAAAADAQABgAaABwAAHgAqADoAAAEwHQEUBwMOAS4BNxMjIiY0NjMhOwEwMjMeARccATEBIREhESE1MxUhNTMTETQmIyEiBhURFBYzITI2BIACgAYuMxwHbK4aJiYaAQACAQIBFyADAQABAPqAAQCAAoCAgEs1/IA1S0s1A4A1SwTDAQIIB/4AGhsMLhkBsSY0JgIgFwEBAbv7AAUAgICA+4ACgDVLSzX9gDVLSwAADAEAAYAGgAcAAAMABwALAA8AEwAXABsAHwArADsAPwBDAAABNTMVAzUzFQM1MxUBNTMVAzUzFSE1MxUBNTMVMzUzFREhESERITUzFSE1MxMRNCYjISIGFREUFjMhMjYBNTMVAzUzFQMAgICAgID+gICAgAKAgP6AgICAAQD6gAEAgAKAgIBLNfyANUtLNQOANUv+AICAgAKAgIABAICAAQCAgP4AgIABAICAgIABAICAgIACAPsABQCAgID7gAKANUtLNf2ANUtLATWAgP8AgIAAAAACAVUBVQd6B3oACwAgAAAJARcBDgMHPgIBNwEHJiIPAQ4BFhcHATcWMj8BNjQB3gIfWv3hJDs6JyIMFDgC+LQCH7Ulaia1GBISGLT94LUmaia1JQI4Ah9a/eElLx0OCS4zUgS8tf3gtCUltRlCQhi1Ah+0JSW2JWoAAAAAAgEAAQAHAAcAABAAHAAAAQcBBiMiJAIQEiQgBBIVFAcAFB4BMj4BNC4BIgYHAID+EZi5nP72mpoBCgE4AQqab/xveM70znh4zvTOAYCAAe9vmgEKATgBCpqa/vacuZgBy/TOeHjO9M54eAAAAwEAAQAHAAcAABAAHAAgAAAJAQcBBiMiJAIQEiQgBBIVFAAyPgE0LgEiDgEUFhM1IRUFEQHvgP4RmLmc/vaamgEKATgBCpr9RvTOeHjO9M54eAgCgANv/hGAAe9vmgEKATgBCpqa/vacuf75eM70znh4zvTOAQiAgAAAAAMBAAEABwAHAAALABwAKAAAAREhFSERIxEhNSERCQEHAQYjIiQCEBIkIAQSFRQAMj4BNC4BIg4BFBYDgAEA/wCA/wABAAIRAe+A/hGYuZz+9pqaAQoBOAEKmv1G9M54eM70znh4BgD/AID/AAEAgAEA/W/+EYAB72+aAQoBOAEKmpr+9py5/vl4zvTOeHjO9M4AAAAFAAABKwgABtUADQAcAB0AJQAtAAAJAgYEICQnCQE2JCAEAwkBLgEiBgcJAR4BMzI2EwQQNiAWEAYgAhQWMjY0JiIGBQH7/gVk/vT+1v70Zf4GAfplAQwBKgEMJQF1/o1NxdjETP6MAXJNxWxsxU/9AOEBPuHh/sJhS2pLS2oF+/4F/gVmc3NnAfoB+mdzc/wrAXQBc05TUk7+jP6NTlNSAcKfAT7h4f7C4QI1aktLaksAAAAFAAABKwgABtUABwAXACMAKwA7AAABIicBFhUUBgkCBgQjIic3FjMyNjcBJxMXASc3CQE2JDMyFwAyNjQmIgYUJTcmIyIGBwkBNyY1NDYzMgQAGSEBtAbhAgEBYP4FZP70lamck15UbMVLAXXZLoH7AIGA/joB+mUBDJX3yf2LaktLaksBzWqPqGzETP6MAT5xP+GfbAKABgG0IRmf4QLg/qD+BWZzT5MiUk4BdNgB4oH7AIGAAcYB+mdzoP3MS2pLS2r2amlSTv6M/sJxYG2f4QAAAAECgAKABgAGAAALAAAJAgcJAScJATcJAQYA/sABQID+wP7AgAFA/sCAAUABQAWA/sD+wIABQP7AgAFAAUCA/sABQAAAAQCAAIAIAAgAAAsAAAkCBwkBJwkBNwkBCAD8wANAgPzA/MCAA0D8wIADQANAB4D8wPzAgANA/MCAA0ADQID8wANAAAADAYABgAYABoAAEwAfADUAAAEFFSsINSU0NjMhMhYHMjY0JiMhIgYUFjMFMxEUBiMhIiY1ETMRMxEzETMRMxEzBQABAICAgICAgICAgAEASzUBgDVLwBomJhr/ABomJhoBwIBLNf2ANUuAgICAgIAGAICAgIA1S0u1JjQmJjQmwP1ANUtLNQLA/UACwP1AAsD9QAAAAQEAAR0HAAaWAAkAAAkBEwkBEwEFGwEHAP4kt/4l/iW3/iQCTLS0BH/+tv3pAUz+tAIXAUoBAhf96QAAAgGAAgAGgAaAAAYACgAACQEHESERJwERIREEAAKAgPwAgAMA/wAGgP4AgP4AAgCA/cABwP5AAAACAQACAAcABgAABAAJAAABIRUJARUJAREhAQAGAP0A/QADAAMA+gAGAID+gAGAwP6AAYD9QAAAAAQBgAGABsAGwAAEAAgADgASAAAJAiERCQEXCQE3LwIHJRcBJwUAAcD8gP5AA4D9rWACU/2ggGBAYIABTWACU2AGwP5A/IABwALA/a1gAlP8YIBgQGCADWACU2AAAQEAAMAHgAbAAAgAAAkBESERAREhEQeA/YD8AAGAAoADQP2AAcACwAGA/UABwAAAAwEAAQAHAAcAAAwAHAAkAAABMgQeAhIVITQCJCMRMgwBABoBFSE0CgEmLAEjEjIWFAYiJjQBAIsBCuC9hEr/AM7+ntDRAY4BUQEcxm7/AFyl7f7n/rWucKBwcKBwBQBKhL3g/vaL0AFizgMAbsb+5P6v/nLRrgFLARntpVz8gHCgcHCgAAAAAAP/+QEACAYHvwASABoAHgAAAR4BDgEjISIuAjY3AT4BMhYXADI2NCYiBhQbASETB8wrDjR0U/nsQmc8FxcjAvgrcHJwK/73aktLakvZNP7mMwJaRoBdNyNAVWo4BNVGSUlG+tFLaktLagE1AoD9gAADAIABgAeABoAAFQArADMAAAEhESEGBCMiLgEnNyY0NjIXHgEzMjYBIgYVIREhNiQzMhYXFhQGIicHLgICNDYyFhQGIgWAAgD+ykv+w8JXpY06ASZLaiY1i02f4f6An+H+AAE2SwE9woLoWSZLaiYBI1Nj9HCgcHCgBAD/AKzULlQ7ASVqSyU2PeECH+GfAQCs1GRZJWpLJQEkMh3+MKBwcKBwAAECAAGABYAHAAArAAAAIBYVERQOASIuATURMxEUFiA2NRE0JiMiBhURFBYyNjURMxEUBiMiJjURNAO7AQq7eM70zniAuwEKu3FPUHAmNCaAcU9QcAcAu4X9gHrOeHjOegFA/sCFu7uFAoBPcXBQ/gAaJiYaAcT+PE9xcFACAIUAAgGAAZEGAAcAAA4AGAAAACAEEhUUBgcJAS4BNTQSATI2ECYjIgYQFgMkATgBCppZUP5p/mlQWZoBpoS8vISFu7sHAJr+9px101D+aQGXUNN1nAEK/Rq8AQi8u/72uwAAAQJgAoAGAAXgAAYAAAEXASMBNxcFgID+AID+4IDgBeBg/QABoIDAAAMAAAEACAAHAAADAAcACwAAGQEhEQEhESEZASERCAD4AAgA+AAIAAEAAQD/AAYA/wD9gAEA/wAAAgEAAQAHAAcAABMAKQAAASchEScOAhUUEhcRLgICNTQSARQOAQcXIREfAT4BNTQuAScRHgISAePjAoDoL0Ql2aeH7KtieAWIOGVG4/2AE9VIUGSubofsq2IGHeP9gOgucIVFsf7vLP76FonGAQOMnAEW/k5oxqhH4wKAE9VGumh1zo4dAQYWicb+/QABAYADgAYABIAAAwAAAREhEQGABIADgAEA/wAAAgGAAgAGAAYAAAMABwAAASERISURIREBgASA+4AEAPyABgD8AIACgP2AAAAEAFMCQAgABeAABwAPABcAHwAACQEhESMRIQkBIREjESEBFwQgFhAGICYQEjI2NCYiBhQCOP71AZOA/hMBdQSlAZOA/hMBdXD8QwEKu7v+9rvxnnFxnnEFof4f/oABAAKf/eH+gAEAAp8+Ybv+9ru7AQr+u3GecXGeAAAAAwEAAQAHAAcAAAcADwATAAAJAREBIQERAQAyNjQmIgYUGwEhEwWAAYD+gP0A/oABgAFLaktLakvZNP7mMwcA/oD9AP6AAYADAAGA+wBLaktLagE1AoD9gAAAAAAJAYABgAYABwAABwAPABcAGwAfACsANwA/AEMAAAAyFhQGIiY0EjIWFAYiJjQSMhYUBiImNCU1IRUBNSEVESERIREhNDYzITIWBSIGFBYzITI2NCYjAREjFSE1IxEBNSEVAqY0JiY0JiY0JiY0JiY0JiY0JgEAAYD+gAGAAQD7gAEASzUBgDVL/kAaJiYaAQAaJiYaAUCA/YCAAYABgAQAJjQmJjQBJiY0JiY0/iYmNCYmNKaAgP8AgIAEAPsABQA1S0s1JjQmJjQm+4AEAICA/AACgICAAAABAIACAAeABgAAHAAAATIWFAYjISImNDY7ASY1NDYzMhYXPgEzMhYVFAcGgGqWlmr7AGqWlmoHB7uFQnYsLrxyn+EYBACW1JaW1JYfIYW7My1le+GfPkIAAgGAAYAHAQcFABMAFwAAARYUDwEOAScBIREBJyY0PwE2MhcDNwEHBrZLS+lK0Uv+Of7gAccBSkrpS9RKWKD/AKAFnEvTS+lKAUj+OQEgAccBStRL6UpK/ZagAQCgAAAAAQMAAwAFAAUAAAcAAAAyFhQGIiY0A5bUlpbUlgUAltSWltQAAQGAAdIF7gWuAAgAAAkCJwEhNSEBBAAB7f4TVwFX/IADgP6pBa3+E/4TVgFXgAFXAAAAAAECEgHSBoAFrgAIAAABFwEhFSEBBwEEAFf+qQOA/IABV1f+EwWtVv6pgP6pVgHtAAEBgAJABgAFAAAFAAABFwkBNwEFgID9wP3AgAHABQCA/cACQID+QAABAYACgAYABUAABQAACQInCQEFgP5A/kCAAkACQAKAAcD+QIACQP3AAAAAAAEAAAAAA4ADgAACAAARASEDgPyAA4D8gAAAAAABBIAAAAgAA4AAAgAAIQERBIADgAOA/IAAAAAAAgGAAgAGgAWAAAIABgAACQMhFSEBgAKAAoD7AAUA+wACAAKA/YADgIAAAAAQAgACgAWABgAAAwAHAAsADwATABcAGwAfACMAJwArAC8AMwA3ADsAPwAAATUzFTM1MxUzNTMVNzMVIwE1MxUzNTMVMzUzFTM1MxUBNTMVMzUzFTM1MxUzNTMVATUzFTM1MxUzNTMVMzUzFQIAgICAgICAgID9AICAgICAgID8gICAgICAgID8gICAgICAgIAFgICAgICAgICA/wCAgICAgICAgP8AgICAgICAgID/AICAgICAgICAAAAAAAMCAAEABgAHAAAPABcAGwAAATIWFREUBiMhIiY1ETQ2MxIyNjQmIgYUAREhEQUAapaWav4AapaWastqS0tqSwIA/QAHAJZq/ABqlpZqBABqlvqAS2pLS2oBNQMA/QAAAAMBAAEABgAHAAAXAB8AJgAAATIWFREUBiMhIiY1ETMVIREhFSM1NDYzEjI2NCYiBhQDNSERITUBBQBqlpZq/gBqloADAP0AgJZqy2pLS2pLgP4AAgABgAcAlmr8AGqWlmoBgIADAICAapb6gEtqS0tqAbWAAQCA/wAAAAADAYABAAaABwAABwAPABsAAAERIRE0NjIWBREhETQ2MhYBIRQCBgcRIREuAQIDgP8AS2pLAgD/AEtqS/wABQCG6ZH/AJHphgaA/oABgDVLSzX+gAGANUtL/cuY/vWzHf7zAQ0dswELAAIAgAAAB4AGAAAGACgAAAERIQkBIREBMhYUBiMhESERISImNDY7ASY1NDYzMh4BFz4BMzIWFRQHBIABAP6A/oABAAMAapaWav6A/gD+gGqWlmoGBruFLFRHHS68cp/hGAKA/wD+gAGAAQABgJbUlgEA/wCW1JYgIIW7FyseZXvhnz5CAAEAgAIAB4AGAAAkAAABMhYUBiMhESEJASERISImNDY7ASY1NDYzMh4BFz4BMzIWFRQHBoBqlpZq/gABAP6A/oABAP4AapaWagYGu4UsVEcdLrxyn+EYBACW1JYBAAGA/oD/AJbUliAghbsXKx5le+GfPkIAAgIAAgAGgAaAAAkAEgAAARE3ESERIQchEQEhESMRAScBIQUAgPyAAgCA/wABgAKAgP3aWgIm/loCgAEAgP4AA4CA/YAEAP2AAab92loCJgACAgABgAYABoAABwAPAAAJAR0BESERIQERISM1ESERBIABgPwAAgABgP8AgP6ABoD+gHkH/QAFAPuAAoCAAQD8AAAAAAIBgAEABoAHAAARABsAAAEiBhQWOwEVISImNRE0NjMhEQEhJjQ3ISIGFBYGQDVLSzVA/ABqlpZqBAD8AAMyMjL8zjVLSwKAS2pLgJZqBABqlvuA/wA3kjdLaksAAgCgAJ8HYAdgACwANAAAAQclBgcTBycGIicHJxMmJwUnNyY1NDcnNwU2NwM3FzYyFzcXAxYXJRcHFhQHBDQmIgYUFjIHYDr+zy88FovJPxo+yYsVOzD+zzroCAjoOgExMDsVi8lBFEHJjBY7MAExOugICP6IltSWltQC7IwWPC/+zzroCAjoOgExLzwWi8k/DQtAyYsVPC8BMTroCAjoOv7PLzwWjMg/Gj4f1JaW1JYAAAAAAwEAAQAHAAcAAAsAFAAdAAAAIAQSEAIEICQCEBIBNC4BIyIHATYlFB4BMzI3AQYDLwGiAWHOzv6f/l7+n87OBDKJ7IuIewK7SPwAieyLiHv9RUgHAM7+n/5e/p/OzgFhAaIBYf3Oi+yJSP1Fe4iL7IlIArt7AAAAAwEAAQAHAAcAAAcADwAbAAAAMhYUBiImNCQyFhQGIiY0ASEVIRUhESE1IREhBUtqS0tqS/1LaktLaksEAPyAA4D8AP8AAYAEgAIAS2pLS2pLS2pLS2oBy4CABACA/wAAAgIAAYAGAAaAAAMABwAAAREhEQEhESECAAGAAQABgP6AAYAFAPsABQD7AAABAgACAAYABgAAAwAAAREhEQIABAACAAQA/AAAAgEAAYAHAAaAAAIABgAACQERIREhEQMABAD6AAGABAACgPsABQD7AAAAAAACAQABgAcABoAAAgAGAAABEQETIREhAQAEAIABgP6AAYAFAP2AAoD7AAAAAAECAAGABgAGgAACAAAJAgIABAD8AAaA/YD9gAADAQAAAAcACAAADwAXABsAAAEyFhURFAYjISImNRE0NjMAMjY0JiIGFAERIREGAGqWlmr8AGqWlmoBy2pLS2pLAoD8AAgAlmr6AGqWlmoGAGqW+IBLaktLagE1BQD7AAADAIAAAAcACAAABgAeACYAAAE1IREhNQkBMhYVERQGIyEiJjURIREhESERIRE0NjMAMjY0JiIGFAKA/gACAAGAAgBqlpZq/ABqlgEABAD8AP8AlmoBy2pLS2pLA4CAAQCA/wADgJZq+gBqlpZqAoD+gAUA/oABgGqW+IBLaktLagAAAAADAQABAAcABwAACwATAB0AAAAgBBIQAgQgJAIQEgQiBhQWMjY0EzUjESEVMxEjFQMvAaIBYc7O/p/+Xv6fzs4CZ2pLS2pLgKD+wICgBwDO/p/+Xv6fzs4BYQGiAWEyS2pLS2r8S4ACAID+gIAAAAAAAwEAAQAHAAcAAAsAEwAXAAAAIAQSEAIEICQCEBIAMjY0JiIGFBsBIRMDLwGiAWHOzv6f/l7+n87OAf1qS0tqS9k0/uYzBwDO/p/+Xv6fzs4BYQGiAWH7zktqS0tqATUCgP2AAAMBAAEABwAHAAALABMAMwAAACAEEhACBCAkAhASADI2NCYiBhQBNjU0JyYjIgcXNjMyFxYVFAcGBwYHBh0BMzU0NzY3NgMvAaIBYc7O/p/+Xv6fzs4B/WpLS2pLAb8lVFSUtKRchmQoGRoYGTREGxrMERJFUgcAzv6f/l7+n87OAWEBogFh+85LaktLagI5OlFwQEFetEcQEBwjHBsiKi0sQTkiHRQVLTQAAAABAIABgAeABoAABgAACQERAREBEQeA/AD9AAMABAD9gAHg/iAFAP4gAeAAAAEAgAGAB4AGgAAGAAABEQERCQERB4D9APwABAAGgPsAAeD+IAKAAoD+IAAABAEAAgAHAAYAAAcACwASABYAAAEzASEBMxMhATMnIyUTASMBMxsBMycjBoCA/wD9AAEAgFYBVP7r1iuA/epW/wCA/wCAVj/WK4AFAP0AAwABAP8AgID/AP0AAwABAP8AgAAAAAEA8wGABw0GjgARAAAJAS4BPgIWHwE3PgEeAgYHBAD9eEk7J4S5vkmhoUm+uIUoPEkBgAJlRcPHmz4qRZiYRSo+m8jCRQAAAAMAZgHgB5oGIAAFAAsADwAAAScJATcDAQcTAxcJARcBJwJr1v7RAS/W0QTR1tHR1gEv+2r4AQD4BTmO/jn+OY4BOQHHjv7H/seOAcf+Hz4EAD4AAAQAAAEACAAGAAAEAAkAGQAlAAAJAjUhCQElESEBMhYVERQGIyEiJjURNDYzATUhESMRIRUhETMRBgD9AP0ABgD6AAMAAQD8AAeANUtLNf2ANUtLNQKA/wCA/wABAIAFgP6AAYCA/sD+gID+QAKASzX9gDVLSzUCgDVL/gCAAQD/AID/AAEAAAAEAAABAAgABgAABAAJABkAHQAACQI1IQkBJREhATIWFREUBiMhIiY1ETQ2MwE1IRUGAP0A/QAGAPoAAwABAPwAB4A1S0s1/YA1S0s1AoD9gAWA/oABgID+wP6AgP5AAoBLNf2ANUtLNQKANUv+AICAAAAAAAQAAAEACAAGAAAEAAkAGQAfAAAJAjUhCQElESEBMhYVERQGIyEiJjURNDYzEwEnAScHBgD9AP0ABgD6AAMAAQD8AAeANUtLNf2ANUtLNfwBxFr+lrVbBYD+gAGAgP7A/oCA/kACgEs1/YA1S0s1AoA1S/0AAcRb/pa1WwACAAABgAeABoAABQAUAAAJAhEJAjIeARURJy4BIyERCQERAoD+wAFA/YACgAMAi+yJlkq8ZP8A/YACgAVA/sD+wP7AAoACgP6AieyL/tSWSkz+gAKAAoD+gAAAAAEBgAGABwAGgAAOAAABMh4BFREnLgEjIREJAREFAIvsiZZKvGT/AP2AAoAFAInsi/7UlkpM/oACgAKA/oAAAAACAQABAAcABwAAAwAfAAABESERASERISIuAyMiDgMjETI+AzMyHgMBAAEABAABAP8ARm9LS29GR2w+MzkjIzkzPmxHRm9LS28BAAYA+gAFgP0AGiYmGhomJhoDABomJhoaJiYaAAAAAAMBAAEABwAGgAAHAAsAGAAAASERIREhESEBESERARQWHwEhJy4CPQEhAQAGAP8A/AD/AASA/QADADk4cP0AcCUzGQMABQD9AAGA/oAEgP8AAQD8AEuNN3FxJFpfMoAAAAIBgAEABoAHAAAXAB8AAAEyFhURFAYjISImNRE0NjM1ND4BIB4BFQUhNTQmIgYVBgA1S0s1/AA1S0s1iewBFuyJ/QACAJbUlgSASzX9gDVLSzUCgDVLgIvsiYnsi4CAapaWagADAgACAAVXBoAAEAAaACIAAAEhMhcWFRQGBxUeARUUBiMhATMyNjU0JyYrARkBMzI2NTQjAgABZ/Rvb2FQbWHkw/5RAQCCZFkxMWh1k2VgzAaARkWZZ4QOBxmGb52xArg9R0IdHf4+/tRNUI8AAAAAAQKAAgAFgAYAAAsAAAEjAzMHITczEyM3IQVYgPCAKP5AKIDwgCgBwAWA/QCAgAMAgAAAAAMBgAGABoAGgAADAAsAEQAAASERIQAiBhQWMjY0AREnAQMBAYAFAPsAAbVqS0tqSwKAgP5AwP8ABoD7AAQAS2pLS2r8ywJAwP1gASD+gAAACQCAAQAHgAcAAAIABgAJAAwADwASABUAGAAbAAATESETESEREyERCQEpAQERCQEXCQEHJQkBAzcBgAGAgAMAgAGA+QABgP6ABYABgP6AAQCA/oABgID5gAGA/wCAgAEABYABgPwAAgD+AAQA/oD9AP6AAYD+gASAAYCA/AD/AICAAQD+gAWAgP6AAAADAQABAAcABwAACwASAMEAAAAgBBIQAgQgJAIQEhcnBgc/AgEyJDcnNy8CDwEvAj8HFz8BHwEmLwEPBCc/ARc3Jz8CJicHFycHFw8DJzcvAj8CJiMiBzcfATcXPwEfATcPAh8CPwIfATcfAQ8BNwcfAQc3DwgnKwEPARc3DwEvBBcHLwUGFRQSFhcvBT8CJwcnPwIHNx8EBzcHHwMPAycXDwEyFgMvAaIBYc7O/p/+Xv6fzs4OAwMKBREeAgDEAUBKBg8jGRg4NCgnAQEFBRcNEw0lJhtDGhgNFwUOHRcaMxgDDS8IGBUoD0xzBBQhBBUIPE08BhAMLhYgRR5rYtWvJjAgIy8eBhwLMEskNw0nGyITISEJHQsUSzYqBQ4LLhAaHw4jGgogGggYLicxBh06DyknLDIWBQgBCAUKBQEaHnzYiAQKC0MgCgcOCAgPFA08JwIPE0QxIgkIIQgvMB8CFxwyKCQRAiEEKgcAzv6f/l7+n87OAWEBogFh9QQGEwEGA/xO2bAKMxkIExUDHTYgNwcSIw4UGiMBCgclCjw2BQcCFiMLCSgaAxYaCRYLeEsCEQUKAgkKIx08IRUUEQgRASWHAQwICAYHEgMXBRkVKg8SHCImFxESCjcUExYMERAHExMFDxETFBgaPBowKCsgHisaCRJPMBBCEQoRDBckLmNTkf7/siQMij9COBwQNT4FCwkHDRIbGQcWIhMFMQkQCwQTOkFEH1sFFxEaBgAAAAMAoAMgB2AE4AAHAA8AFwAAADIWFAYiJjQkMhYUBiImNCQyFhQGIiY0ASO6g4O6gwMDuoODuoMDA7qDg7qDBOCDuoODuoODuoODuoODuoODugAAAAEAgAAACAADwAACAAApAQEIAPiAA8ADwAAAAAABAAAAgAPACAAAAgAANREBA8CAB4D8QAABAIAEQAgACAAAAgAAEyEBgAeA/EAIAPxAAAAAAQRAAIAIAAgAAAIAAAERAQgA/EAIAPiAA8AAAAMBgAEABoAHAAAoADAAOAAAARQGBxUUDgEjIgYdASERLgE1NDYyFhUUDgEHETYzMjY9AS4BNTQ2MhYkIgYUFjI2NAQyNjQmIgYUBoBGOonsi2qW/wA6RpbUliA6JnqGapY6RpbUlvw1aktLaksCS2pLS2pLBgBGdSKji+yJlmqABCMidkVqlpZqLlZCF/4WR5ZqoyJ1RmqWlhZLaktLarVLaktLagAAAAYBAAGABwAGgAADAAcACwAPABMAFwAAAREhEQEhESEBESERAREhEQERIREhESERAQABAAEABAD8AP4AAQADgP2A/gABAAEAA4AFgAEA/wABAP8A/gABAP8AAQD/AAEA/QABAP8AAQD/AAAAAAMBNwEABwAHgAANACsAMwAACQMmNDcBJz4EARYVFAYjIicBNScmBg8BBiIvAQEXFhQPAQ4BHwEzEjI2NCYiBhQDAAHp/YD+8yUlASUBBREtIRwDyjZqS0s2/rZAGlslTCVqJQ8CgA8lJUwlDxpAgLA1JiY1JQeA/hf9gAENJWomASQDBRVHUoX6/jVMS2o2AUqAQBoPJUwlJQ8CgA8laiVMJVsaQP31JjUlJTUAAAAABQCAAIAHgAeAAEQATABUAFwAZAAAAR4BFRQGIiY1ND4BNzU0JiMhER4BFRQGIiY1NDY3ESEiBh0BHgEVFAYiJjU0Njc1NDYzIREuATU0NjIWFRQGBxEhMhYVACIGFBYyNjQAMjY0JiIGFAQyNjQmIgYUBDI2NCYiBhQHADpGltSWIDomSzX/ADpGltSWRjr/ADVLOkaW1JZGOuGfAQA6RpbUlkY6AQCf4f01aktLakv8y2pLS2pLAstqS0tqSwLLaktLaksCXSJ1RmqWlmouVkIXozVL/t0idUZqlpZqRXYiASNLNaMidkVqlpZqRXYio5/hASMidkVqlpZqRnUi/t3hnwQAS2pLS2r6S0tqS0tqS0tqS0tqS0tqS0tqAAAAAgBUAOEHQAbAABIAGgAAAR4BMzI2MwkCAwkBNxcBEwkBADIWFAYiJjQFqiNxQgMLAv5w/wD/AID/AP7U5UcBAIABAAEAATCgcHCgcAVzNT4C/OACAP4AAQD+AAJXc44CAP8AAgD+AAKicKBwcKAAAAIBbgEABpIHAAAhACkAAAEXBgQgJCc3HgEXESM1MzUuATU0NjIWFRQGBxUzFSMRPgEAIgYUFjI2NAX+lGf+o/5k/qNnlEbFc4CAOkaW1JZGOoCAc8X+fWpLS2pLAs5Zq8rLqllKZhMB9YCjInZFapaWakZ1IqOA/gsTZQP9S2pLS2oAAAIAgACAB4AHAABOAFwAAAEyFhQGKwEGBxYSHQEUBiImPQE0JwYEIyIkJwYdARQGIiY9ATQSNyYnIyImNDY7ATQ3JhE1NDYyFh0BFB4CID4CPQE0NjIWHQEQBxYVJSImJz4BMzIeARcOAgdAGiYmGs0NIlpiJjQmglr+9pqZ/vVZgyY0JmNZIQ7NGiYmGsAdnSY0JmWs7QEE7axlJjQmnBz9gJr9PVryiFutkTsoi7oEACY0JkFKZ/7/jUAaJiYaQNard4qJd6zUQBomJhpAjQEBZ0lCJjQmUGDOAQJAGiYmGkCC7axlZaztgkAaJiYaQP7/zltWgKmJYW0zW0Baik4AAAAAAgGAAYAGgAaAAAYACgAACQIhESERASERIQWA/oD+gAEAAQD9AAUA+wAEgP6AAYACAP4A/gD/AAABAQABAAcABwAAEQAAARYzESIsAQAKATUhFBcHFgAXBcidm9H+cv6v/uTGbgIAar1mATK7AzMz/gBuxgEcAVEBjtHt1r2x/u9SAAAAAgHGAQAGOgcAAA0AHQAAACImNRE0NjMyHgEVERQ3MwYCBxEhESYCJzMeASA2BFCfcXFPNFkzucAU9LH/ALH0FMAX1QEb1AOAcU8CAE9xM1k0/gBQELf+8Cn+8AEQKQEQt4m3twAAAAABAYADgAaABIAAAwAAAREhEQGABQADgAEA/wAAAQCAAIAHgAeAABcAAAkBESERIQkBIREhEQkBESERIQkBIREhEQeA/oD+gAEA/oD+gAEA/oD+gAGAAYD/AAGAAYD/AAGABAD+gAEA/oD+gAGAAYD/AAGAAYD/AAGAAYD+gP6AAQAAAAABAYABgAaABoAACwAAAREhESERIREhESERBoD+AP8A/gACAAEABID/AP4AAgABAAIA/gAAAgCAAQAHgAeAAAkAEwAAAQMhBQMlBQMlIQMTIQETCQETASEEAHb+jQEsdgEzATR3ASz+jXbTAq391dX91v3W1f3VAq0F5/6Z0v6f29sBYdIDAP2A/nz9hAGK/nYCfAGEAAAAAAEAgAEAB4AHgAAJAAAJARMJARMBIRsBB4D91dX91v3W1f3VAq3T0wUA/nz9hAGK/nYCfAGEAoD9gAAAAAIAgAEAB4AHgAAJAA8AAAkBEwkBEwEhGwEDBQMlIQMHgP3V1f3W/dbV/dUCrdPT0wE0dwEs/o12BQD+fP2EAYr+dgJ8AYQCgP2A/ijbAWHSAWcAAAMBAAGAB4AGgAAWACIAKwAAATUJATUhIi4BNTQmIyERITIeARUUFjMRIgcmJzYzITUJATUBMjcWFwYjIREGgAEA/wD/AIvsiZZq/oABgIvsiZZqWkgpV4OfAQABAP8A/ABaSClXg5/+gAMAgP8A/wCAieyLapYBAInsi2qWAgA7fmJbgP8A/wCA/gA7fmJbAQAAAAAEAIAAgAeAB4AADwAtAEkAYgAAACAEFhIQAgYEICQmAhASNgEyPgE1NC4BJyYhIg4BBw4CFRQWMzYzNjMyFhcWNzI2NTQnJiQjIg4BBwYVFBYXMjYzNjMyBBcyFhMyNjU0JyYkIyIHBhUUFjMyNjM2MzIEFxYDSAFwAUzvjY3v/rT+kP60742N7wNqEx4PCQ8O8f7kNnpMRBERERkaGg2zZn/wXg2AHCQniP6yqkeMT0QzLh8GGgZzs6QBJmoMGoAeLzOU/oLV/KpAMyYPIAWsursBWHoZB4CN7/60/pD+tO+Nje8BTAFwAUzv+2cPFw0TGA4HjRESEQgLGxIVHg0aOzkM5i8eORROWBERERE8HDQKDSdKQw0BGjQlMxpcVzMVRSYzDSZPSwwAAAAEAIAAgAeAB4AAAwAHABEAGQAAAREjESERIxEBIREBIQMjESERAREhESEVNyEEAJwCHJz8XwY9/i3+oerk/gAGZPr7AV/pAawFrP4tAdP+LQHTAdT7vf5D/wABAATI/UMDWfuW09MAAAEBAAIABwAGAAATAAAJAREBERQGIyEiJjURNDYzITIWFQWAAYD+gEs1/IA1S0s1A4A1SwSAAYD8AAGA/wA1S0s1AwA1S0s1AAAADgCuAAEAAAAAAAAAIQBEAAEAAAAAAAEACgB8AAEAAAAAAAIABwCXAAEAAAAAAAMAJwDvAAEAAAAAAAQACgEtAAEAAAAAAAUAEAFaAAEAAAAAAAYACgGBAAMAAQQJAAAAQgAAAAMAAQQJAAEAFABmAAMAAQQJAAIADgCHAAMAAQQJAAMATgCfAAMAAQQJAAQAFAEXAAMAAQQJAAUAIAE4AAMAAQQJAAYAFAFrAEMAbwBwAHkAcgBpAGcAaAB0ACAAKABjACkAIAAyADAAMQA2ACwAIABKAG8AZQBuACAAQQBzAG0AdQBzAHMAZQBuAABDb3B5cmlnaHQgKGMpIDIwMTYsIEpvZW4gQXNtdXNzZW4AAEcAZQBuAGUAcgBpAGMAbwBuAHMAAEdlbmVyaWNvbnMAAFIAZQBnAHUAbABhAHIAAFJlZ3VsYXIAAEYAbwBuAHQARgBvAHIAZwBlACAAMgAuADAAIAA6ACAARwBlAG4AZQByAGkAYwBvAG4AcwAgADoAIAAxADUALQAxADEALQAyADAAMQA2AABGb250Rm9yZ2UgMi4wIDogR2VuZXJpY29ucyA6IDE1LTExLTIwMTYAAEcAZQBuAGUAcgBpAGMAbwBuAHMAAEdlbmVyaWNvbnMAAFYAZQByAHMAaQBvAG4AIAAwADAAMQAuADAAMAAwACAAAFZlcnNpb24gMDAxLjAwMCAAAEcAZQBuAGUAcgBpAGMAbwBuAHMAAEdlbmVyaWNvbnMAAAAAAgAAAAAAAP8AAGYAAAAAAAAAAAAAAAAAAAAAAAAAAACXAAAAAQACAAMBAgEDAQQBBQEGAQcBCAEJAQoBCwEMAQ0BDgEPARABEQESARMBFAEVARYBFwEYARkBGgEbARwBHQEeAR8BIAEhASIBIwEkASUBJgEnASgBKQEqASsBLAEtAS4BLwEwATEBMgEzATQBNQE2ATcBOAE5AToBOwE8AT0BPgE/AUABQQFCAUMBRAFFAUYBRwFIAUkBSgFLAUwBTQFOAU8BUAFRAVIBUwFUAVUBVgFXAVgBWQFaAVsBXAFdAV4BXwFgAWEBYgFjAWQBZQFmAWcBaAFpAWoBawFsAW0BbgFvAXABcQFyAXMBdAF1AXYBdwF4AXkBegF7AXwBfQF+AX8BgAGBAYIBgwGEAYUBhgGHAYgBiQGKAYsBjAGNAY4BjwGQAZEBkgGTAZQHdW5pRjEwMAd1bmlGMTAxB3VuaUYxMDIHdW5pRjEwMwd1bmlGMTA0B3VuaUYxMDUHdW5pRjEwNgd1bmlGMTA3B3VuaUYxMDgHdW5pRjEwOQd1bmlGMjAwB3VuaUYyMDEHdW5pRjIwMgd1bmlGMjAzB3VuaUYyMDQHdW5pRjIwNQd1bmlGMjA2B3VuaUYyMDcHdW5pRjIwOAd1bmlGMjA5B3VuaUYyMTAHdW5pRjIxMQd1bmlGMjEyB3VuaUYyMTMHdW5pRjIxNAd1bmlGMjE1B3VuaUYyMTYHdW5pRjIxNwd1bmlGMjE4B3VuaUYyMTkHdW5pRjIyMAd1bmlGMjIxB3VuaUYyMjIHdW5pRjIyMwd1bmlGMjI0B3VuaUYyMjUHdW5pRjIyNgd1bmlGMzAwB3VuaUYzMDEHdW5pRjMwMgd1bmlGMzAzB3VuaUYzMDQHdW5pRjMwNQd1bmlGMzA2B3VuaUYzMDcHdW5pRjMwOAd1bmlGNDAwB3VuaUY0MDEHdW5pRjQwMgd1bmlGNDAzB3VuaUY0MDQHdW5pRjQwNQd1bmlGNDA2B3VuaUY0MDcHdW5pRjQwOAd1bmlGNDA5B3VuaUY0MTAHdW5pRjQxMQd1bmlGNDEyB3VuaUY0MTMHdW5pRjQxNAd1bmlGNDE1B3VuaUY0MTYHdW5pRjQxNwd1bmlGNDE4B3VuaUY0MTkHdW5pRjQyMAd1bmlGNDIxB3VuaUY0MjIHdW5pRjQyMwd1bmlGNDI0B3VuaUY0MjUHdW5pRjQyNgd1bmlGNDI3B3VuaUY0MjgHdW5pRjQyOQd1bmlGNDMwB3VuaUY0MzEHdW5pRjQzMgd1bmlGNDMzB3VuaUY0MzQHdW5pRjQzNQd1bmlGNDM2B3VuaUY0MzcHdW5pRjQzOAd1bmlGNDM5B3VuaUY0NDAHdW5pRjQ0MQd1bmlGNDQyB3VuaUY0NDMHdW5pRjQ0NAd1bmlGNDQ1B3VuaUY0NDYHdW5pRjQ0Nwd1bmlGNDQ4B3VuaUY0NDkHdW5pRjQ1MAd1bmlGNDUxB3VuaUY0NTIHdW5pRjQ1Mwd1bmlGNDU0B3VuaUY0NTUHdW5pRjQ1Ngd1bmlGNDU3B3VuaUY0NTgHdW5pRjQ1OQd1bmlGNDYwB3VuaUY0NjEHdW5pRjQ2Mgd1bmlGNDYzB3VuaUY0NjQHdW5pRjQ2NQd1bmlGNDY2B3VuaUY0NjcHdW5pRjQ2OAd1bmlGNDY5B3VuaUY0NzAHdW5pRjQ3MQd1bmlGNDcyB3VuaUY0NzMHdW5pRjQ3NAd1bmlGNDc1B3VuaUY0NzYHdW5pRjUwMAd1bmlGNTAxB3VuaUY1MDIHdW5pRjUwMwd1bmlGNTA0B3VuaUY1MDUHdW5pRjUwNgd1bmlGNTA3B3VuaUY1MDgHdW5pRjUwOQd1bmlGNTBBB3VuaUY1MEIHdW5pRjUwQwd1bmlGNTBEB3VuaUY1MEUHdW5pRjUwRgd1bmlGNTEwB3VuaUY1MTEHdW5pRjUxMgd1bmlGNTEzB3VuaUY1MTQHdW5pRjUxNQd1bmlGNTE2B3VuaUY1MTcAAAAB//8AAgAAAAEAAAAA0ywqSAAAAADUUNkwAAAAANRQ2TE=');
      //doc.addFont(`Genericons.ttf`, 'Genericons', 'normal');
      //doc.setFont('Genericons');
      doc.text("表单数据", 10, 10);

      const columns = ["mno", "mname", "mmode", "mefficacy"];
      const rows = this.medicines.map(medicine => [
        medicine.mno,
        medicine.mname,
        medicine.mmode,
        medicine.mefficacy
      ]);

      doc.autoTable({
        head: [columns],
        body: rows
      });

      doc.save('药品表单数据.pdf');
    }
  },
  mounted() {
    this.fetchMedicines();
  }
};
</script>

<style scoped>
.el-table {
  border: 1px solid #eaecef;
  border-radius: 8px;
  overflow: hidden;
}

.el-table th, .el-table td {
  padding: 16px;
  text-align: center; /* 中心对齐内容 */
}

.el-table th {
  background-color: #f5f7fa;
  color: #333;
  font-weight: bold;
}

.el-table td {
  transition: background-color 0.3s ease;
}

.el-table td:hover {
  background-color: #f0f0f0; /* 鼠标悬停时的背景颜色 */
}

@media (max-width: 768px) {
  .el-table {
    font-size: 12px; /* 在小屏幕上减小字体 */
  }
  .el-table th, .el-table td {
    padding: 10px; /* 在小屏幕上减小内边距 */
  }
}
</style>
